import {
  BookUser,
  Building2,
  Bus,
  ChartColumn,
  FileText,
  Gauge,
  IdCard,
  KeyRound,
  Landmark,
  LayoutDashboard,
  List,
  ListChecks,
  Network,
  Receipt,
  ScanLine,
  ShieldCheck,
  Sticker,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

import type { NavIcon } from "@/lib/navigation";

/** The drawing for each icon the navigation table names. */
export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  overview: LayoutDashboard,
  verify: ScanLine,
  applications: FileText,
  members: BookUser,
  cards: IdCard,
  vehicles: Bus,
  stickers: Sticker,
  fees: Receipt,
  settlement: Landmark,
  organisations: Building2,
  profiles: ListChecks,
  limits: Gauge,
  structure: Network,
  lists: List,
  officers: Users,
  roles: KeyRound,
  security: ShieldCheck,
  account: UserRound,
  usage: ChartColumn,
};
