/**
 * @nurtw/contracts — shared types consumed by both the API and the web application.
 *
 * ARCHITECTURE.md Decision 3.1: response types are declared once here and imported
 * by the web application, so that a change to a response shape produces a compile
 * error rather than a runtime defect.
 *
 * Zod schemas live here too (ARCHITECTURE.md §3), introduced at item 04 where the
 * first request bodies large enough to warrant them appear. The API validates
 * against them and the dashboard reuses them for forms, so one definition governs
 * both sides of every request.
 */

export {
  CARD_STATUSES,
  DECLARATION_STATUSES,
  STICKER_STATUSES,
  VERIFIABLE_DECLARATION_STATUSES,
  VERIFIABLE_STICKER_STATUSES,
  type CardStatus,
  type DeclarationStatus,
  type StickerStatus,
} from './statuses.js';

export {
  ANAMBRA_LGA_SEED,
  ANAMBRA_STATE_NAME,
  DESIGNATION_SEED,
  LEGACY_VEHICLE_CATEGORY_SEED,
  ORGANISATION_LEVELS,
  ROUTE_TYPE_SEED,
  type MasterDataSeedEntry,
  type OrganisationLevel,
} from './master-data.js';

export { loginSchema, type LoginInput } from './auth.js';

export {
  assignRoleSchema,
  changePasswordSchema,
  createRoleSchema,
  createUserSchema,
  reasonSchema,
  scopedPermissionSchema,
  secondFactorSchema,
  setSecondFactorEnforcementSchema,
  setUserStatusSchema,
  updateRoleSchema,
  updateUserSchema,
  type AccountState,
  type AssignRoleInput,
  type ChangePasswordInput,
  type CreateRoleInput,
  type CreateUserInput,
  type IssuedTemporaryPassword,
  type OrganisationRef,
  type ReasonInput,
  type RoleSummary,
  type ScopedPermissionInput,
  type SecondFactorConfirmed,
  type SecondFactorEnrolment,
  type SecondFactorInput,
  type SecuritySettings,
  type SetSecondFactorEnforcementInput,
  type SetUserStatusInput,
  type UpdateRoleInput,
  type UpdateUserInput,
  type UserDetail,
  type UserRoleAssignmentSummary,
  type UserScopedPermission,
  type UserSummary,
} from './users.js';

export {
  MASTER_DATA_COLLECTIONS,
  createLgaSchema,
  createMasterDataSchema,
  createOrganisationSchema,
  moveOrganisationSchema,
  organisationLevelSchema,
  setOrganisationActiveSchema,
  updateLgaSchema,
  updateMasterDataSchema,
  updateOrganisationSchema,
  type CreateLgaInput,
  type CreateMasterDataInput,
  type CreateOrganisationInput,
  type LgaEntry,
  type MasterDataCollection,
  type MasterDataEntry,
  type MoveOrganisationInput,
  type OrganisationNode,
  type OrganisationTreeNode,
  type SetOrganisationActiveInput,
  type UpdateLgaInput,
  type UpdateMasterDataInput,
  type UpdateOrganisationInput,
} from './organisation.js';

export {
  AGGREGATE_FILTERED_SCOPE,
  AGGREGATE_TOTAL_SCOPE,
  API_SCOPES,
  API_SCOPE_DESCRIPTIONS,
  DEFAULT_AGGREGATE_SUPPRESSION_FLOOR,
  DEFAULT_TOKEN_EXPIRY_DAYS,
  DEFAULT_TOKEN_REMINDER_DAYS,
  isApiScope,
  type ApiScope,
} from './scopes.js';

export {
  SETTABLE_API_CLIENT_STATUSES,
  apiScopeSchema,
  approveApiClientSchema,
  registerApiClientSchema,
  revokeApiTokenSchema,
  rotateApiTokenSchema,
  setApiClientAccessSchema,
  setApiClientStatusSchema,
  updateApiClientSchema,
  type ApiClientDetail,
  type ApiClientList,
  type ApiClientSummary,
  type ApiTokenSummary,
  type ApproveApiClientInput,
  type IssuedApiToken,
  type RegisterApiClientInput,
  type RevokeApiTokenInput,
  type RotateApiTokenInput,
  type SetApiClientAccessInput,
  type SetApiClientStatusInput,
  type UpdateApiClientInput,
} from './api-client.js';

export {
  aggregateTotalQuerySchema,
  aggregateVehicleQuerySchema,
  type AggregateFiltersApplied,
  type AggregateVehicleQuery,
  type AggregateVehicleResponse,
  type OrganisationMetadataResponse,
} from './aggregate.js';

export {
  ABUSE_SIGNAL_LABELS,
  DEFAULT_RATE_LIMIT_PROFILE,
  SYSTEM_RATE_LIMIT_PROFILES,
  createRateLimitProfileSchema,
  liftApiClientPauseSchema,
  setApiClientLimitsSchema,
  updateRateLimitProfileSchema,
  type ApiClientLimits,
  type ApiClientPause,
  type CreateRateLimitProfileInput,
  type LiftApiClientPauseInput,
  type RateLimitProfileSummary,
  type RateLimitProfileValues,
  type SetApiClientLimitsInput,
  type SystemRateLimitProfile,
  type UpdateRateLimitProfileInput,
} from './rate-limit.js';

export {
  DISCLOSURE_FIELD_LABELS,
  SYSTEM_DISCLOSURE_PROFILES,
  createDisclosureProfileSchema,
  updateDisclosureProfileSchema,
  type CreateDisclosureProfileInput,
  type DisclosureFieldCheck,
  type DisclosureProfileSummary,
  type SystemDisclosureProfile,
  type UpdateDisclosureProfileInput,
} from './disclosure.js';

export {
  ATTACH_STICKER_PERMISSION,
  DECLARE_PERMISSION,
  MANAGE_SETTLEMENT_PERMISSION,
  RECORD_VEHICLE_PERMISSION,
  PERMISSIONS,
  PERMISSION_CODES,
  SYSTEM_ROLES,
  type PermissionCode,
  type PermissionDefinition,
  type RoleDefinition,
  type SystemRoleCode,
} from './permissions.js';

export {
  APPLICATION_DECISIONS,
  applicantSchema,
  attachMediaSchema,
  createApplicationSchema,
  guarantorSchema,
  nextOfKinSchema,
  organisationalAssignmentSchema,
  reviewApplicationSchema,
  setMemberStatusSchema,
  updateApplicationSchema,
  withdrawApplicationSchema,
  type ApplicantInput,
  type ApplicationDecision,
  type ApplicationDetail,
  type ApplicationSummary,
  type AttachMediaInput,
  type CreateApplicationInput,
  type GuarantorInput,
  type MemberSearchResult,
  type NextOfKinInput,
  type OrganisationalAssignmentInput,
  type ReviewApplicationInput,
  type SetMemberStatusInput,
  type UpdateApplicationInput,
  type WithdrawApplicationInput,
} from './membership.js';

export {
  OFFICER_SIGNATURE_POSITIONS,
  createOfficerSignatureSchema,
  decideCardSchema,
  draftCardSchema,
  officerSignaturePositionSchema,
  replaceCardSchema,
  setCardStatusSchema,
  updateCardSchema,
  type CardDetail,
  type CardSummary,
  type CreateOfficerSignatureInput,
  type DecideCardInput,
  type DraftCardInput,
  type OfficerSignaturePosition,
  type OfficerSignatureRecord,
  type ReplaceCardInput,
  type SetCardStatusInput,
  type UpdateCardInput,
} from './card.js';

export {
  SETTABLE_DECLARATION_STATUSES,
  declareRecordedVehicleSchema,
  declareVehicleSchema,
  dismissDisputeSchema,
  recordVehicleSchema,
  setDeclarationStatusSchema,
  updateVehicleSchema,
  vehicleOwnerSchema,
  type DeclareRecordedVehicleInput,
  type DeclareVehicleInput,
  type DismissDisputeInput,
  type RecordVehicleInput,
  type SetDeclarationStatusInput,
  type UpdateVehicleInput,
  type VehicleDetail,
  type VehicleOwnerDetail,
  type VehicleOwnerInput,
  type VehicleSummary,
} from './vehicle.js';

export {
  assignDedicatedAccountSchema,
  initiatePaymentSchema,
  payLinkSubjectSchema,
  publicPaySchema,
  refundPaymentSchema,
  replacePayLinkSchema,
  resolveSettlementAccountSchema,
  setDedicatedPercentageSchema,
  setFeeTypePriceSchema,
  setSettlementAccountSchema,
  updateFeeTypeSchema,
  type AmountToSend,
  type AssignDedicatedAccountInput,
  type DedicatedAccountAllocation,
  type DedicatedAccountState,
  type DedicatedAccountTransfer,
  type DedicatedAccountUnassignableReason,
  type DuesStatusCode,
  type FeeTypeSummary,
  type InitiatePaymentInput,
  type MemberDues,
  type PayLinkSubjectInput,
  type PayLinkSummary,
  type PaystackBank,
  type PublicPayInput,
  type PublicPayOption,
  type PublicPayPage,
  type PublicPayStarted,
  type RefundPaymentInput,
  type ReplacePayLinkInput,
  type ResolvedSettlementAccount,
  type ResolveSettlementAccountInput,
  type SetDedicatedPercentageInput,
  type SetFeeTypePriceInput,
  type SetSettlementAccountInput,
  type SettlementState,
  type UnpaidLevyMonth,
  type UpdateFeeTypeInput,
  type VehicleDues,
} from './payments.js';

export {
  attachStickerSchema,
  issueStickerSchema,
  legacyBarcodeLookupSchema,
  reissueVehicleLetterSchema,
  setStickerStatusSchema,
  type AttachStickerInput,
  type EligibleOnboardingPayment,
  type IssueStickerInput,
  type LegacyBarcodeLookupInput,
  type OnboardingState,
  type ReissueVehicleLetterInput,
  type SetStickerStatusInput,
  type VehicleOnboarding,
} from './sticker.js';

export {
  externalCombinedVerificationSchema,
  externalMembershipVerificationSchema,
  externalPlateVerificationSchema,
  externalStickerVerificationSchema,
  verifyMembershipSchema,
  verifySchema,
  type ExternalCombinedVerificationInput,
  type ExternalMembershipVerificationInput,
  type ExternalPlateVerificationInput,
  type ExternalStickerVerificationInput,
  type ExternalVerificationResponse,
  type InternalMembershipVerification,
  type InternalVerification,
  type VerificationDues,
  type VerifyInput,
  type VerifyMembershipInput,
} from './verification.js';
